### ISSUE TITLE
Sprint Tasks

### ISSUE THREAD

**Issue by gidden** [IAMconsortium/concordia#18]
# Tasks

- [x] regenerate latest harmonization (@coroa)
- [x] Debug failing runs on IIASA infrastructure (@gidden)
- [x] Develop upload (ftp/ssh/rysnc) infrastructure for BCS (@gidden )
- [ ] Generate CDR proxy map with C-storage + renewable potential (@coroa)
- [ ] ~Downscaler supports `remove_invalid_proxy_regions('proxy.nc')`~ concordia workflow supports removing isos with 0 gridding proxies (@coroa)
- Finish input4mips consistency for dimensions/attributes, etc. (@gidden)
	- [x] concat shipping sector back with anthro 
	- [x] Update complevel to 2 
	- [x] Add version to sourceid 
	- other consistency
		- [x] clean coords
		- [x] clean vars
		- [x] var attrs
		- [x] bnds
		- [x] ds attrs
		- [x] fill value
		- [x] filename
- Minimal tests for (using, e.g., xarray example of CAN/USA/MEX, two regions NAM=[CAN|USA]/MEX) (@coroa)
	- [ ] Harmonizer
	- [ ] Downscaler
	- [ ] Gridder
- Minimal docs for (@coroa)
	- [ ] Harmonizer
	- [ ] Downscaler
	- [ ] Gridder
	- [ ] Docs describing how to generate a workflow, using concordia as a basis
- Generate releases (@coroa)
	- [ ] aneris
	- [ ] concordia
- Provide gridded data for current datasets (@gidden)
	- [x] generate gridded data
	- [x] upload data 
- Coordinate initial testing with ESMs (@gidden)
	- [x] communicate with MAgPIE on location/uploading data (provide bash scripts for rsync, etc.)
	- [x] send email to focal points on how to locate/provide feedback
	- [x] send email to WP2 people on final location of harmonized outputs
	- [x] develop issue template and process when generating new datasets
- Future outlook
- Regression tests
	- [ ] Implement testing hook for BCS when generating (call their verification function when creating grids)
	- [ ] (nice to have) set up regression tests on IIASA infrastructure
